### ISSUE TITLE
TCK Challenge: The ManagedBeanTypesTest test fails with Java 21 with the 4.0.x TCK

### ISSUE THREAD

**Issue by jamezp** [jakartaee/cdi-tck#485]
The `ManagedBeanTypesTest` test fails on Java 21 in the 4.0.x TCK because of the new `SequencedCollection`. This was fixed in #477, however only for 4.1.x.

When running the 4.0.11 TCK with Java 21 the following failure occurs:
```
Failed Tests:
org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest
    testGenericHierarchyBeanTypes - Time elapsed: 0.065 [FAILED]
        Reason: Set [interface java.util.SequencedCollection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, class java.lang.Object, interface java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, interface java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (6) does not match array [class java.lang.Object, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (5)


***************************************************************
Total: 718 - PASSED: 717 - FAILED: 1 - ERRORS: 0 - SKIPPED: 0
***************************************************************
```

It's the intention of TCK's to work on new versions of Java than the minimum, see https://github.com/jakartaee/cdi-tck/issues/484#issuecomment-1749191084. It seems back-porting the fix would likely be enough for 4.0.x or simply excluding the test.

**Comment by Ladicek** [comment]
At this point, I think we should just add an exclusion to 4.0 TCK, as 4.1 is not very far away.

**Comment by jbescos** [comment]
Same issue in Helidon.

**Comment by manovotn** [comment]
@jamezp @jbescos today or later this week I plan to release a new TCK 4.0 version with the two challenges addressed.

**Comment by jamezp** [comment]
Excellent, thank you!

**Comment by manovotn** [comment]
FYI, TCK 4.0.12 is now available in Central.

**Comment by jamezp** [comment]
@manovotn Awesome, thank you! Do you my chance know when it will be available on https://download.eclipse.org/jakartaee/cdi/4.0/?

**Comment by manovotn** [comment]
> @manovotn Awesome, thank you! Do you my chance know when it will be available on https://download.eclipse.org/jakartaee/cdi/4.0/? IIRC it happens when [jakartaee/specifications#659](https://github.com/jakartaee/specifications/pull/659) is merged, right?

TBF I don't know how exactly this works.
In the release job there are some `scp` commands that transferred the new `.zip` file just fine. Therefore, I'd also assume it's based on the PR :shrug:

**Comment by starksm64** [comment]
The project CI job can only copy the candidate release binary to the
project download area. Promotion of this binary to the jakarta download
area requires a spec committee member to run another promotion job, so the
actionable step for the cdi project is to create an update to the current
cdi specification page in the https://github.com/jakartaee/specifications
repo and then create a PR. At that point someone from the spec committee
can promote the binary and merge the updated spec page.

**Comment by struberg** [comment]
Maybe I did read this wrong, but I did assume this test got fixed in 4.0.12, right? But the check is still in there and thus fails because the TCK test doesn't expect `SequencedCollection<Vulture<Integer>>`. Should I reopen this ticket or file a new one?

**Comment by Ladicek** [comment]
It was fixed on the `master` branch for CDI 4.1, and added to the exclusion list for CDI 4.0.

**Comment by struberg** [comment]
Oki, txs for clarifying.

**Comment by jbescos** [comment]
Hello, I am trying it with the version 4.0.13 and still fails:

```
[ERROR] Failures: 
[ERROR]   ManagedBeanTypesTest>Arquillian.run:138->testGenericHierarchyBeanTypes:80 Set [interface java.util.SequencedCollection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, class java.lang.Object, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, interface java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, interface java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, class org.jboss.cdi.tck.tests.definition.bean.types.Flock] (6) does not match array [class java.lang.Object, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (5)
```

**Comment by Ladicek** [comment]
That is correct. This test was added to an exclusion list for CDI 4.0, so you should [feel free to] skip it [when running on 21].
